### ISSUE TITLE
Pantheon/name

### ISSUE THREAD

**Issue by r0kur0ta** [elementary/brand#17]
### Problem

Having monotheist religion background I feel uncomfortable to use Pantheon DE, you know the first thing Google gives for "pantheon" is "(temple) of roman gods". 

### Proposal

Would you consider please to change the name of DE, from "Pantheon" to something neutral, I don't mean to hurt or bother you, just suggesting. However, the other point(other from "distro culture") to consider in distros is user experience and how smooth everything works, and I admit that elementary is the best I have ever experienced. Thanks to you elementary OS team. But just if you would change DE name... Please consider, and thanks for reading

**Comment by danrabbit** [comment]
Hey there. Sorry to hear that you're bothered by this brand name. All of our code releases are based on mythical figures and deities. This is one of the ways we celebrate the multiple cultures in our great and diverse world. I hope you enjoy using our software, but I think this is unlikely to change
