### ISSUE TITLE
Conflicting/Confusing primary blue(berry)

### ISSUE THREAD

**Issue by louis993546** [elementary/brand#9]
During a [pull request for another repo](https://github.com/simple-icons/simple-icons/pull/1047), we found out that the color is a little bit weird:

1. In the README here, Blueberry = `#3892e0`
2. In the branding page, Blueberry on the top = `#3689e6`, which is 500, but the text of it is white on the "header" and gray in the list
3. In `logomark-blue.svg`, the background is `#64BAFF`, which is Blueberry 300 on the branding page

At the end we have decided to go with Blueberry 300 `#64BAFF`, but anyway I think either the page or this repo needs to clarify what the primary blue should be.

Thanks!

**Comment by birjolaxew** [comment]
Relevant #3

**Comment by cassidyjames** [comment]
We've restructured this repo which included the removal of the conflicting README and the blue marks; now they are just in monochrome. We should re-order the color section to clarify that Blueberry is our primary color, but otherwise this has been resolved.
